
#VLAN-k létrehozása és interfacek konfigurálása:
network:
    ethernets:
        eno1:
            addresses:
            - 172.16.200.94/22

            routes:
            - to: 0.0.0.0/0
              via: 172.16.200.1
            match:
                macaddress: c4:54:44:60:35:e5
            mtu: 1500
            nameservers:
                addresses:
                - 172.16.200.251
                search:
                - maas
            set-name: eno1
        enp3s0f1:
            match:
                macaddress: c4:54:44:60:35:e6
            mtu: 1500
            optional: true
            set-name: enp3s0f1
        enp6s0f0:
            addresses:
            - 10.10.0.1/18
            match:
                macaddress: 08:9e:01:92:2d:94
            mtu: 1500
            optional: true
            set-name: enp6s0f0
        enp6s0f1:
            addresses:
            - 172.16.232.5/24
            gateway4: 172.16.232.252
            match:
                macaddress: 08:9e:01:92:2d:95
            mtu: 1500
            nameservers:
                addresses:
                - 8.8.4.4
                - 8.8.8.8
                search:
                - maas
            routes:
            -   table: 1
                to: 0.0.0.0/0
                via: 172.16.232.252
            routing-policy:
            -   from: 172.16.232.0/24
                priority: 100
                table: 1
            -   from: 172.16.232.0/24
                table: 254
                to: 172.16.232.0/24
            set-name: enp6s0f1
vlans:
      vlan100:
        id: 100
        link: enp6s0f1
        addresses:
        - 10.100.0.254/24
      vlan200:
        id: 200
        link: enp6s0f1
        addresses:
        - 10.200.0.254/24


