apiVersion: v1
kind: Pod
metadata:
  name: ecmpfe1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.11/24" ],
              "mac": "c2:b0:57:49:47:f7",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.11/24" ],
              "mac": "c2:b0:57:49:47:f8"
            }
            ]'
spec:
  nodeName: worker1
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: frontendubuntu:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true

---
apiVersion: v1
kind: Pod
metadata:
  name: Ecmpfe2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.12/24" ],
              "mac": "c2:b0:57:49:47:f9",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.12/24" ],
              "mac": "c2:b0:57:49:47:fa"
            }
            ]'
spec:

  nodeName: worker2
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: frontendubuntu:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true

---
apiVersion: v1
kind: Pod
metadata:
  name: Ecmpfe3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan100",
              "ips": [ "10.100.0.13/24" ],
              "mac": "c2:b0:57:49:47:fb",
              "gateway": [ "10.100.0.254" ],
              "default-route": ["10.100.0.254" ]
            },
            { "name": "macvlan200",
              "ips": [ "10.200.0.13/24" ],
              "mac": "c2:b0:57:49:47:fc"
            }
            ]'
spec:
  nodeName: worker3
  hostAliases:
  - ip: "10.200.0.253"
    hostnames:
    - "hello"
  containers:
  - name: teszt
    image: frontendubuntu:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
#    lifecycle:
#      preStop:
#        exec:
#          command: ["/usr/sbin/nginx","-s","quit"]
    securityContext:
      capabilities:
        add:
          - ALL
      privileged: true